#!/usr/bin/env python3
"""Generate text preprocessing fixtures from the Python CTC reference."""

from __future__ import annotations

import argparse
import pathlib
import sys
import types


CASES = [
    {
        "name": "plain_english",
        "language": "eng",
        "split_size": "word",
        "text": "Hello, WORLD!",
    },
    {
        "name": "apostrophes",
        "language": "eng",
        "split_size": "word",
        "text": "Don’t stop, I'm yours",
    },
    {
        "name": "punctuation_digits",
        "language": "eng",
        "split_size": "word",
        "text": "Track 01: go!!! 2024",
    },
    {
        "name": "accents",
        "language": "eng",
        "split_size": "word",
        "text": "Café coração déjà vu",
    },
    {
        "name": "brackets_blank_lines",
        "language": "eng",
        "split_size": "word",
        "text": "[Verse]\n\nHello again",
    },
    {
        "name": "english_char",
        "language": "eng",
        "split_size": "char",
        "text": "Hi, yo!",
    },
    {
        "name": "japanese_force_char",
        "language": "jpn",
        "split_size": "word",
        "text": "歌う猫",
    },
    {
        "name": "chinese_force_char",
        "language": "chi",
        "split_size": "word",
        "text": "你好！",
    },
    {
        "name": "portuguese_soltasbruxa",
        "language": "por",
        "split_size": "word",
        "text": "Soltasbruxa no meio da rua\nNão sei se volto",
    },
    {
        "name": "german_ich_will",
        "language": "deu",
        "split_size": "word",
        "text": "Ich will, dass ihr mir vertraut",
    },
]


class MissingUroman:
    def romanize_string(self, *_args: object, **_kwargs: object) -> str:
        raise RuntimeError("uroman is required for romanized fixtures")


def install_uroman_fallback() -> None:
    try:
        import uroman  # noqa: F401
    except ModuleNotFoundError:
        module = types.ModuleType("uroman")
        module.Uroman = MissingUroman
        sys.modules["uroman"] = module


def repo_root() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parents[1]


def import_reference_text_utils():
    root = repo_root()
    reference = root / "ctc-reference" / "ctc-forced-aligner"
    package_dir = reference / "ctc_forced_aligner"

    install_uroman_fallback()

    package = types.ModuleType("ctc_forced_aligner")
    package.__path__ = [str(package_dir)]
    sys.modules["ctc_forced_aligner"] = package

    import ctc_forced_aligner.text_utils as text_utils

    return text_utils


def hex_utf8(text: str) -> str:
    return text.encode("utf-8").hex()


def effective_split_size(language: str, split_size: str) -> str:
    if language in ["jpn", "chi"]:
        return "char"
    return split_size


def write_list(out, name: str, values: list[str]) -> None:
    for value in values:
        out.write(f"{name}\t{hex_utf8(value)}\n")


def generate(path: pathlib.Path) -> None:
    text_utils = import_reference_text_utils()

    with path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("# Generated by tools/generate_ctc_reference_fixtures.py.\n")
        out.write(
            "# Do not edit by hand; update the generator and regenerate.\n"
        )
        out.write("format\t1\n")

        for case in CASES:
            language = case["language"]
            split_size = case["split_size"]
            actual_split_size = effective_split_size(language, split_size)
            text = case["text"]

            text_split = text_utils.split_text(text, actual_split_size)
            normalized = [
                text_utils.text_normalize(chunk.strip(), language)
                for chunk in text_split
            ]
            tokens = [" ".join(list(word)) for word in normalized]
            edges_tokens, edges_text = text_utils.preprocess_text(
                text,
                romanize=False,
                language=language,
                split_size=split_size,
                star_frequency="edges",
            )
            segment_tokens, segment_text = text_utils.preprocess_text(
                text,
                romanize=False,
                language=language,
                split_size=split_size,
                star_frequency="segment",
            )

            out.write(f"fixture\t{case['name']}\n")
            out.write(f"language\t{language}\n")
            out.write(f"split_size\t{split_size}\n")
            out.write(f"effective_split_size\t{actual_split_size}\n")
            out.write("romanize\tfalse\n")
            out.write(f"input\t{hex_utf8(text)}\n")
            write_list(out, "text_split", text_split)
            write_list(out, "normalized", normalized)
            write_list(out, "tokens", tokens)
            write_list(out, "edges_tokens", edges_tokens)
            write_list(out, "edges_text", edges_text)
            write_list(out, "segment_tokens", segment_tokens)
            write_list(out, "segment_text", segment_text)
            out.write("end\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default="testdata/ctc_text_reference_fixtures.txt",
        help="fixture output path relative to the repository root",
    )
    args = parser.parse_args()

    output = pathlib.Path(args.output)
    if not output.is_absolute():
        output = repo_root() / output

    output.parent.mkdir(parents=True, exist_ok=True)
    generate(output)


if __name__ == "__main__":
    main()
