#if !defined(LRC_DEFAULT_MODELS_H)
#define LRC_DEFAULT_MODELS_H

#if !defined(LRC_DEFAULT_MODEL_DIR)
#define LRC_DEFAULT_MODEL_DIR "models"
#endif

#if !defined(LRC_SYSTEM_MODEL_DIR)
#define LRC_SYSTEM_MODEL_DIR "/usr/share/lyricsync/models"
#endif

#if !defined(LRC_LOCAL_SYSTEM_MODEL_DIR)
#define LRC_LOCAL_SYSTEM_MODEL_DIR "/usr/local/share/lyricsync/models"
#endif

#define LRC_DEFAULT_VOCALS_MODEL_REL_PATH "UVR-MDX-NET-Voc_FT.onnx"
#define LRC_DEFAULT_CTC_MODEL_REL_PATH "mms-onnx/onnx/model.onnx"
#define LRC_DEFAULT_CTC_TOKENIZER_REL_PATH "mms-onnx/tokens.txt"

#define LRC_DEFAULT_VOCALS_MODEL_PATH \
    LRC_DEFAULT_MODEL_DIR "/" LRC_DEFAULT_VOCALS_MODEL_REL_PATH
#define LRC_DEFAULT_CTC_MODEL_PATH \
    LRC_DEFAULT_MODEL_DIR "/" LRC_DEFAULT_CTC_MODEL_REL_PATH
#define LRC_DEFAULT_CTC_TOKENIZER_PATH \
    LRC_DEFAULT_MODEL_DIR "/" LRC_DEFAULT_CTC_TOKENIZER_REL_PATH

#define LRC_SYSTEM_VOCALS_MODEL_PATH \
    LRC_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_VOCALS_MODEL_REL_PATH
#define LRC_SYSTEM_CTC_MODEL_PATH \
    LRC_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_CTC_MODEL_REL_PATH
#define LRC_SYSTEM_CTC_TOKENIZER_PATH \
    LRC_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_CTC_TOKENIZER_REL_PATH

#define LRC_LOCAL_SYSTEM_VOCALS_MODEL_PATH \
    LRC_LOCAL_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_VOCALS_MODEL_REL_PATH
#define LRC_LOCAL_SYSTEM_CTC_MODEL_PATH \
    LRC_LOCAL_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_CTC_MODEL_REL_PATH
#define LRC_LOCAL_SYSTEM_CTC_TOKENIZER_PATH \
    LRC_LOCAL_SYSTEM_MODEL_DIR "/" LRC_DEFAULT_CTC_TOKENIZER_REL_PATH

#endif /* LRC_DEFAULT_MODELS_H */
